version: "3.9"
services:

  # connection redirection (Proxy)
  # - nginx
  # - traefik
  
  
  # email
  # - iRedMail 
  
  
  # email online client
  # - RoundCube

  # website
  # - apache
  # - ningx
  
  
  # Let's Encrypt!
  # https
      
  
  # video schooling
  # - zoom
  # - jitsi
  
  
  # video plattform for uploads
  # - Kaltura
  # - bamboo-video
  
  # Authentication
  # - keycloak
  # - OpenLDAP
  
    
  # Project:
  # - gitlab
  
  
  # file sharing
  # - nextcloud
  # - moodle
  # - teaching like (grips)
  
  # Database
  # - mysql
  # - mariadb
  # ...